export { ArrowDiagonal } from "./ArrowDiagonal";
export { Phone } from "./Phone";
export { Clock } from "./Clock";
export { Mail } from "./Mail";
export { MapPoint } from "./MapPoint";
export { PhoneHollow } from "./PhoneHollow";
export { Telegram } from "./Telegram";
export { VK } from "./VK";
export { Plus } from "./Plus";
