export {
  type IGallery,
  type IReview,
  type ReviewPayload,
  type IService,
  type IServiceGroup,
  type ServicePayload,
  type ServiceGroupPayload,
  type IDoctor,
  type DoctorPayload,
  type IGalleryItem,
  type GalleryPayload,
  type ICallRequest,
  type CallRequestPayload,
  type IAppointment,
  type AppointmentPayload,
  type INews,
  type NewsPayload,
  type IUser,
  type UserPayload,
} from "./api";
export {
  type IAdvantageCard,
  type IDiagnosticsCard,
  type IEmployeeInfo,
  type IFeedbackForm,
  type IQuestions,
  type IWideImageWrapper,
} from "./blocks";
export {} from "./pages";
export {
  type IAccordion,
  type IButton,
  type ICarousel,
  type IContainer,
  type IDropdown,
  type IInput,
  type IModal,
  type IOption,
  type IPageHeading,
  type IPageLayout,
  type ISelect,
  type ITable,
  type IFilter,
  type IMultipleInput,
  type IFileLoader,
  type IAppointmentModal,
  type ICheckbox,
} from "./ui";
export { type IHeader } from "./common";
